INSERT  INTO PRICE (VEHICLE_ID,CURRENCY,PRICE,)
VALUES (1,'USD',11000);

INSERT  INTO PRICE (VEHICLE_ID,CURRENCY,PRICE,)
VALUES (2,'USD',12000);

INSERT  INTO PRICE (VEHICLE_ID,CURRENCY,PRICE,)
VALUES (3,'USD',13000);

INSERT  INTO PRICE (VEHICLE_ID,CURRENCY,PRICE,)
VALUES (4,'USD',14000);

INSERT  INTO PRICE (VEHICLE_ID,CURRENCY,PRICE,)
VALUES (5,'USD',15000);

