INSERT  INTO PRICE (ID,CURRENCY,PRICE,VEHICLE_ID)
VALUES (1,'USD',11000,1);

INSERT  INTO PRICE (ID,CURRENCY,PRICE,VEHICLE_ID)
VALUES (2,'USD',12000,2);

INSERT  INTO PRICE (ID,CURRENCY,PRICE,VEHICLE_ID)
VALUES (3,'USD',13000,3);
